=== rhusar/dtf/Configs/dtf-testdefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  JBoss, Home of Professional Open Source
  Copyright 2008, Red Hat Middleware LLC, and individual contributors
  as indicated by the @author tags.
  See the copyright.txt in the distribution for a
  full listing of individual contributors.
  This copyrighted material is made available to anyone wishing to use,
  modify, copy, or redistribute it subject to the terms and conditions
  of the GNU Lesser General Public License, v. 2.1.
  This program is distributed in the hope that it will be useful, but WITHOUT A
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
  PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public License,
  v.2.1 along with this distribution; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  MA  02110-1301, USA.

  (C) 2008,
  @author JBoss Inc.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="action_list">
		<xs:annotation>
			<xs:documentation>Contains a list of actions which must be performed in order to run this test.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="start_task" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Start a task returns immediately</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="jvm_param" minOccurs="0" maxOccurs="unbounded"/>
						</xs:choice>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="location" type="xs:string"/>
						<xs:attribute name="name_list" type="xs:string"/>
						<xs:attribute name="runtime_id" type="xs:string" use="required"/>
						<xs:attribute name="jvm_parameters" type="xs:string"/>
						<xs:attribute name="parameters" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="perform_task" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Perform a task returns once the task is complete</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="jvm_param" minOccurs="0" maxOccurs="unbounded"/>
						</xs:choice>
						<xs:attribute name="id" type="xs:string" use="required"/>
						<xs:attribute name="runtime_id" type="xs:string"/>
						<xs:attribute name="location" type="xs:string"/>
						<xs:attribute name="name_list" type="xs:string"/>
						<xs:attribute name="jvm_parameters" type="xs:string"/>
						<xs:attribute name="parameters" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="terminate_task" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Terminate a task</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="runtime_id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="wait_for_task" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Wait for a task to terminate/complete</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="runtime_id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="configuration">
		<xs:annotation>
			<xs:documentation>This tests configuration</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="runner" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="names_required" type="xs:int"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="default_timeout">
		<xs:complexType>
			<xs:attribute name="value" type="xs:long" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string">
		<xs:annotation>
			<xs:documentation>Description of this test</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="task">
		<xs:annotation>
			<xs:documentation>Tasks to be used within a test group</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="jvm_param" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="runner"/>
			</xs:choice>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="classname" type="xs:string" use="required"/>
			<xs:attribute name="runner" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="timeout" type="xs:long">
				<xs:annotation>
					<xs:documentation>Timeout value is seconds</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="parameter_setting" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="task_declaration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="task" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="test_declaration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="configuration" minOccurs="0"/>
				<xs:element ref="action_list"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="descriptive_name" type="xs:string" use="required"/>
			<xs:attribute name="author" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="test_group">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="task_declaration" minOccurs="0"/>
				<xs:element ref="test_group" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="test_declaration" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="test_set">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="default_timeout" minOccurs="0"/>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element ref="test_group" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jvm_param" type="xs:string"/>
	<xs:element name="param" type="xs:string"/>
	<xs:element name="runner">
		<xs:annotation>
			<xs:documentation>Configuration for runners used to run tasks within this test</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element name="param" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
						<xs:attribute name="value" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rhusar/dtf/tags/DTF_4_0_0_GA/Configs/new-testdefs.xml
<!--
  JBoss, Home of Professional Open Source
  Copyright 2008, Red Hat Middleware LLC, and individual contributors
  as indicated by the @author tags.
  See the copyright.txt in the distribution for a
  full listing of individual contributors.
  This copyrighted material is made available to anyone wishing to use,
  modify, copy, or redistribute it subject to the terms and conditions
  of the GNU Lesser General Public License, v. 2.1.
  This program is distributed in the hope that it will be useful, but WITHOUT A
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
  PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
  You should have received a copy of the GNU Lesser General Public License,
  v.2.1 along with this distribution; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
  MA  02110-1301, USA.

  (C) 2008,
  @author JBoss Inc.
-->

<test_set xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\HPDTF\Configs\dtf-testdefinitions.xsd">
	<default_timeout value="480"/>
	<description>Quick test definition file used for testing purposes.</description>
	<test_group name="DumpRunInformation">
		<task_declaration>
			<task id="DumpRunInformation" classname="DumpRunInformation" runner="UnitTestRunner" type="expect_pass_fail"/>
		</task_declaration>
		<test_declaration id="DumpRunInformation" descriptive_name="Dumps information on software version" author="Richard A. Begg">
			<description>
	  		This test is used to grab the information generated by report.
	  	</description>
			<configuration/>
			<action_list>
				<perform_task id="DumpRunInformation"/>
			</action_list>
		</test_declaration>
	</test_group>
	<test_group name="ArjunaNesting">
		<task_declaration>
			<task id="RecoveryManager" classname="com.arjuna.CosRecovery.RecoveryManager" runner="ServiceRunner" type="expect_ready"/>
			<task id="ArjunaNesting" classname="ArjunaNestingTest" runner="UnitTestRunner" type="expect_pass_fail"/>
		</task_declaration>
		<test_declaration id="ArjunaNesting1" descriptive_name="Arjuna Nesting 1" author="Mark Little">
			<description>
	  			This example demonstrates the difference between an	ArjunaSubtranAwareResource and the
	  			standard OTS version.  An ArjunaSubtranAwareResource always participates within a two-phase
				commit protocol for nested transactions.  Propagation occurs in the same way, however, i.e.,
				if registered using register_subtran_aware then the resource is not propagated to the parent;
				if using register_resource then it will be propagated.  For each nested transaction, it will
				take part in the two-phase protocol.  This test registers the resource with 'register_resource'
				and commits the top-level transaction.
	  		</description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="ArjunaNesting"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="ArjunaNesting2" descriptive_name="Arjuna Nesting 2" author="Mark Little">
			<description>
				This example demonstrates the difference between an	ArjunaSubtranAwareResource and the
	  			standard OTS version.  An ArjunaSubtranAwareResource always participates within a two-phase
				commit protocol for nested transactions.  Propagation occurs in the same way, however, i.e.,
				if registered using register_subtran_aware then the resource is not propagated to the parent;
				if using register_resource then it will be propagated.  For each nested transaction, it will
				take part in the two-phase protocol.  This test registers the resource with 'register_subtran_aware'
				and commits the top-level transaction.
			</description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="ArjunaNesting" parameters="-subtran"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="ArjunaNesting3" descriptive_name="Arjuna Nesting 3" author="Mark Little">
			<description>
				This example demonstrates the difference between an	ArjunaSubtranAwareResource and the
	  			standard OTS version.  An ArjunaSubtranAwareResource always participates within a two-phase
				commit protocol for nested transactions.  Propagation occurs in the same way, however, i.e.,
				if registered using register_subtran_aware then the resource is not propagated to the parent;
				if using register_resource then it will be propagated.  For each nested transaction, it will
				take part in the two-phase protocol.  This test registers the resource with 'register_resource'
				and rolls back the top-level transaction.
			</description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="ArjunaNesting" parameters="-abort"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="ArjunaNesting4" descriptive_name="Arjuna Nesting 4" author="Mark Little">
			<description>
				This example demonstrates the difference between an	ArjunaSubtranAwareResource and the
	  			standard OTS version.  An ArjunaSubtranAwareResource always participates within a two-phase
				commit protocol for nested transactions.  Propagation occurs in the same way, however, i.e.,
				if registered using register_subtran_aware then the resource is not propagated to the parent;
				if using register_resource then it will be propagated.  For each nested transaction, it will
				take part in the two-phase protocol.  This test registers the resource with 'register_subtran_aware'
				and rolls back the top-level transaction.
	  		</description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="ArjunaNesting" parameters="-abort -subtran"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
	</test_group>
	<test_group name="Asynchronous">
		<task_declaration>
			<task id="RecoveryManager" classname="com.arjuna.CosRecovery.RecoveryManager" runner="ServiceRunner" type="expect_ready"/>
			<task id="AsyncTest" classname="AsyncTest" runner="UnitTestRunner" type="expect_pass_fail"/>
		</task_declaration>
		<test_declaration id="AsyncTest1" descriptive_name="Asynchronous 1" author="Mark Little">
			<description>
	  	Unit test generated from tests\Asynchronous.  Has no threading optimisations.
	  </description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="AsyncTest"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="AsyncTest2" descriptive_name="Asynchronous 2" author="Mark Little">
			<description>
	  	Unit test generated from tests\Asynchronous.  ASYNC_PREPARE enabled
	  </description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="AsyncTest" jvm_parameters="-DASYNC_PREPARE=YES"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="AsyncTest3" descriptive_name="Asynchronous 3" author="Mark Little">
			<description>
	  	Unit test generated from tests\Asynchronous.  ASYNC_PREPARE and ASYNC_COMMIT enabled.
	  </description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="AsyncTest" jvm_parameters="-DASYNC_PREPARE=YES -DASYNC_COMMIT=YES"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="AsyncTest4" descriptive_name="Asynchronous 4" author="Mark Little">
			<description>
	  	Unit test generated from tests\Asynchronous.  ASYNC_PREPARE enabled with error in prepare.
	  </description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="AsyncTest" parameters="-errorp" jvm_parameters="-DASYNC_PREPARE=YES"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
		<test_declaration id="AsyncTest5" descriptive_name="Asynchronous 5" author="Mark Little">
			<description>
	  	Unit test generated from tests\Asynchronous.  ASYNC_PREPARE enabled with error in commit.
	  </description>
			<configuration/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
				<perform_task id="AsyncTest" parameters="-errorc" jvm_parameters="-DASYNC_PREPARE=YES"/>
				<terminate_task runtime_id="RcvMngr"/>
			</action_list>
		</test_declaration>
	</test_group>
	<test_group name="Basic">
		<task_declaration>
			<task id="RecoveryManager" classname="com.arjuna.CosRecovery.RecoveryManager" runner="ServiceRunner" type="expect_ready"/>
			<task id="OTSServer" classname="OTS_Server" runner="ServiceRunner" type="expect_ready"/>
			<task id="AdvertiseOTSServer" classname="CosTransactionsTests.AdvertiseOTSServer" runner="UnitTestRunner" type="expect_pass_fail"/>
			<task id="GridServer" classname="GridServer" runner="UnitTestRunner" type="expect_ready"/>
			<task id="GridClient" classname="GridClient" runner="UnitTestRunner" type="expect_pass_fail"/>
		</task_declaration>
		<test_declaration id="GridTest01" descriptive_name="Basic Grid Test" author="Mark Little">
			<description>Unit test generated from tests\Basic
	  </description>
			<configuration names_required="2"/>
			<action_list>
				<start_task id="RecoveryManager" location="all" parameters="-test" runtime_id="RcvMngr"/>
